### PR TITLE
Fixes #47

### LINKED ISSUE #47: Wrong Toast message on Favourites
**Describe the bug**
Wrong popup info in favourite section when reverse swipe is turned on...

**To Reproduce**
1. Install the app 1st time (or force stop-clear data & restart)
2. Go to app settings & turn on reverse swipe
3. Choose any quote as favourite ♥
4. Go to favourite section & swipe left/right
The tutorial popup it gives is wrong info.

**Expected behavior**
When reverse swipe is turned on it should show "_Swipe Right to Share, Swipe Left to Delete_"

**Screenshots**

### PR DESCRIPTION
**Pull request by abhiram-anand**
# PR Info

## Issue Details

 - **Fixes** #47

## Type of change

- **Bug Fix**

### CODE REVIEW

**Review by VishnuSanal — CHANGES_REQUESTED** [review]
@abhiram-anand 

Thanks for the PR!

I'm afraid that this doesn't fix the issue. It's not a reversal of actions.

Please check `sharedPreferenceHelper.isFavActionReversed()` & set the text accordingly. i.e, it should be reversed (as you did now) when this is true & vice versa :)

You can  take reference from the following code

https://github.com/VishnuSanal/Quotes/blob/ca1005f06504d4c1cb68187958160636c2ea3bad/app/src/main/java/phone/vishnu/quotes/fragment/FavoriteFragment.java#L190

https://github.com/VishnuSanal/Quotes/blob/ca1005f06504d4c1cb68187958160636c2ea3bad/app/src/main/java/phone/vishnu/quotes/fragment/FavoriteFragment.java#L222-L224

File: app/src/main/java/phone/vishnu/quotes/fragment/FavoriteFragment.java [hunk 1]
```diff
@@ -173,7 +173,9 @@ private void setUpRecyclerView(final Context context) {
                                 if (sharedPreferenceHelper.getFavHintShownCount() < 2) {
                                     Toast.makeText(
                                                     requireContext(),
-                                                    "Swipe Right to Delete\nSwipe Left to Share",
+                                                    isFavActionReversed
```
Comment (VishnuSanal) [inline app/src/main/java/phone/vishnu/quotes/fragment/FavoriteFragment.java:176]: Declare & give value to this boolean!!

> https://github.com/VishnuSanal/Quotes/blob/ca1005f06504d4c1cb68187958160636c2ea3bad/app/src/main/java/phone/vishnu/quotes/fragment/FavoriteFragment.java#L190

File: app/src/main/java/phone/vishnu/quotes/fragment/FavoriteFragment.java [hunk 2]
```diff
@@ -173,7 +173,9 @@ private void setUpRecyclerView(final Context context) {
...
+                                                            ?   "Swipe Right to Delete\nSwipe Left to Share"
```
Comment (VishnuSanal) [inline app/src/main/java/phone/vishnu/quotes/fragment/FavoriteFragment.java:177]: Swap Left & Right here (when the boolean is true. i.e, reverse is enabled)

**Review by VishnuSanal — CHANGES_REQUESTED** [review]
@abhiram-anand Please see the comments

**Review by VishnuSanal — APPROVED** [review]
Awesome work! 

@abhiram-anand Please make a PR by adding yourself to [THANKS.md](https://github.com/VishnuSanal/Quotes/blob/master/THANKS.md#-contributors---thank-you-for-all-your-works-) :D
